//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceDirectory.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ServiceDirectoryEntities : DbContext
    {
        public ServiceDirectoryEntities()
            : base("name=ServiceDirectoryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tblAddress> tblAddresses { get; set; }
        public DbSet<tblBusinessType> tblBusinessTypes { get; set; }
        public DbSet<tblContact> tblContacts { get; set; }
        public DbSet<tblCountry> tblCountries { get; set; }
        public DbSet<tblCounty> tblCounties { get; set; }
        public DbSet<tblDepartment> tblDepartments { get; set; }
        public DbSet<tblDirectorate> tblDirectorates { get; set; }
        public DbSet<tblFacility> tblFacilities { get; set; }
        public DbSet<tblFunding> tblFundings { get; set; }
        public DbSet<tblGovOfficeRegion> tblGovOfficeRegions { get; set; }
        public DbSet<tblGroupReference> tblGroupReferences { get; set; }
        public DbSet<tblMinorWork> tblMinorWorks { get; set; }
        public DbSet<tblOrganisation> tblOrganisations { get; set; }
        public DbSet<tblOrganisationService> tblOrganisationServices { get; set; }
        public DbSet<tblPremis> tblPremises { get; set; }
        public DbSet<tblPremisesOpeningTime> tblPremisesOpeningTimes { get; set; }
        public DbSet<tblProgramme> tblProgrammes { get; set; }
        public DbSet<tblReferenceData> tblReferenceDatas { get; set; }
        public DbSet<tblRole> tblRoles { get; set; }
        public DbSet<tblService> tblServices { get; set; }
        public DbSet<tblServicePremise> tblServicePremises { get; set; }
        public DbSet<tblSupportingMaterial> tblSupportingMaterials { get; set; }
        public DbSet<tblTeam> tblTeams { get; set; }
        public DbSet<tblTown> tblTowns { get; set; }
        public DbSet<tblTrustDistrict> tblTrustDistricts { get; set; }
        public DbSet<tblTrustRegion> tblTrustRegions { get; set; }
        public DbSet<tblUser> tblUsers { get; set; }
        public DbSet<tblVolunteering> tblVolunteerings { get; set; }
    }
}
