//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceDirectory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBusinessType
    {
        public tblBusinessType()
        {
            this.tblDepartments = new HashSet<tblDepartment>();
            this.tblDirectorates = new HashSet<tblDirectorate>();
            this.tblOrganisations = new HashSet<tblOrganisation>();
            this.tblTeams = new HashSet<tblTeam>();
        }
    
        public System.Guid BusinessID { get; set; }
        public string BusinessName { get; set; }
        public int SICCode { get; set; }
    
        public virtual ICollection<tblDepartment> tblDepartments { get; set; }
        public virtual ICollection<tblDirectorate> tblDirectorates { get; set; }
        public virtual ICollection<tblOrganisation> tblOrganisations { get; set; }
        public virtual ICollection<tblTeam> tblTeams { get; set; }
    }
}
