//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceDirectory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCounty
    {
        public tblCounty()
        {
            this.tblGovOfficeRegions = new HashSet<tblGovOfficeRegion>();
            this.tblTowns = new HashSet<tblTown>();
        }
    
        public int CountyID { get; set; }
        public Nullable<int> CountryID { get; set; }
        public string CountyName { get; set; }
        public string CountyDescription { get; set; }
    
        public virtual tblCountry tblCountry { get; set; }
        public virtual ICollection<tblGovOfficeRegion> tblGovOfficeRegions { get; set; }
        public virtual ICollection<tblTown> tblTowns { get; set; }
    }
}
