//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceDirectory.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class tblContact
    {
        public tblContact()
        {
            this.tblContact1 = new HashSet<tblContact>();
            this.tblDepartments = new HashSet<tblDepartment>();
            this.tblDirectorates = new HashSet<tblDirectorate>();
            this.tblFacilities = new HashSet<tblFacility>();
            this.tblFacilities1 = new HashSet<tblFacility>();
            this.tblFundings = new HashSet<tblFunding>();
            this.tblMinorWorks = new HashSet<tblMinorWork>();
            this.tblMinorWorks1 = new HashSet<tblMinorWork>();
            this.tblOrganisations = new HashSet<tblOrganisation>();
            this.tblPremises = new HashSet<tblPremis>();
            this.tblPremises1 = new HashSet<tblPremis>();
            this.tblPremises2 = new HashSet<tblPremis>();
            this.tblProgrammes = new HashSet<tblProgramme>();
            this.tblServices = new HashSet<tblService>();
            this.tblTeams = new HashSet<tblTeam>();
            this.tblVolunteerings = new HashSet<tblVolunteering>();
            this.tblReferenceDatas = new HashSet<tblReferenceData>();
        }
    
        public int ContactID { get; set; }
        [Required (ErrorMessage = "Please input FirstName")]
        public string FirstName { get; set; }
        public string Surname { get; set; }
        public string KnownAs { get; set; }
        public string OfficePhone { get; set; }
        public string MobilePhone { get; set; }
        public string StHomePhone { get; set; }
        public string Email { get; set; }
        public Nullable<int> ManagerId { get; set; }
        public string JobRole { get; set; }
        public string Workbase { get; set; }
        public string JobTitle { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual ICollection<tblContact> tblContact1 { get; set; }
        public virtual tblContact tblContact2 { get; set; }
        public virtual ICollection<tblDepartment> tblDepartments { get; set; }
        public virtual ICollection<tblDirectorate> tblDirectorates { get; set; }
        public virtual ICollection<tblFacility> tblFacilities { get; set; }
        public virtual ICollection<tblFacility> tblFacilities1 { get; set; }
        public virtual ICollection<tblFunding> tblFundings { get; set; }
        public virtual ICollection<tblMinorWork> tblMinorWorks { get; set; }
        public virtual ICollection<tblMinorWork> tblMinorWorks1 { get; set; }
        public virtual ICollection<tblOrganisation> tblOrganisations { get; set; }
        public virtual ICollection<tblPremis> tblPremises { get; set; }
        public virtual ICollection<tblPremis> tblPremises1 { get; set; }
        public virtual ICollection<tblPremis> tblPremises2 { get; set; }
        public virtual ICollection<tblProgramme> tblProgrammes { get; set; }
        public virtual ICollection<tblService> tblServices { get; set; }
        public virtual ICollection<tblTeam> tblTeams { get; set; }
        public virtual ICollection<tblVolunteering> tblVolunteerings { get; set; }
        public virtual ICollection<tblReferenceData> tblReferenceDatas { get; set; }
    }
}
