//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceDirectory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCountry
    {
        public tblCountry()
        {
            this.tblCounties = new HashSet<tblCounty>();
            this.tblTrustRegions = new HashSet<tblTrustRegion>();
        }
    
        public System.Guid CountryID { get; set; }
        public string CountryName { get; set; }
        public string CountryDescription { get; set; }
    
        public virtual ICollection<tblCounty> tblCounties { get; set; }
        public virtual ICollection<tblTrustRegion> tblTrustRegions { get; set; }
    }
}
