//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceDirectory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDirectorate
    {
        public tblDirectorate()
        {
            this.tblDepartments = new HashSet<tblDepartment>();
            this.tblMinorWorks = new HashSet<tblMinorWork>();
        }
    
        public System.Guid DirectorateID { get; set; }
        public Nullable<System.Guid> OrgID { get; set; }
        public Nullable<System.Guid> ContactID { get; set; }
        public Nullable<System.Guid> AddressID { get; set; }
        public Nullable<System.Guid> BusinessID { get; set; }
        public string DirectorateName { get; set; }
        public string ShortDescription { get; set; }
        public string FullDescription { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string AddressLine3 { get; set; }
        public string PhoneNumber { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string WebAddress { get; set; }
        public Nullable<int> CharityNumber { get; set; }
        public Nullable<int> CompanyNumber { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual tblAddress tblAddress { get; set; }
        public virtual tblBusinessType tblBusinessType { get; set; }
        public virtual tblContact tblContact { get; set; }
        public virtual ICollection<tblDepartment> tblDepartments { get; set; }
        public virtual tblOrganisation tblOrganisation { get; set; }
        public virtual ICollection<tblMinorWork> tblMinorWorks { get; set; }
    }
}
