//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceDirectory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFacility
    {
        public System.Guid FacilityID { get; set; }
        public Nullable<System.Guid> PremisesID { get; set; }
        public Nullable<System.Guid> FacilityType { get; set; }
        public string ShortDescription { get; set; }
        public Nullable<int> RoomCapacity { get; set; }
        public Nullable<int> RoomSize { get; set; }
        public string ConnectivityType { get; set; }
        public string WireLess { get; set; }
        public Nullable<System.Guid> LeadContactID { get; set; }
        public Nullable<System.Guid> RoomHostID { get; set; }
        public string Notes { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual tblContact tblContact { get; set; }
        public virtual tblContact tblContact1 { get; set; }
        public virtual tblReferenceData tblReferenceData { get; set; }
        public virtual tblPremis tblPremis { get; set; }
    }
}
