//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceDirectory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFunding
    {
        public System.Guid FundingID { get; set; }
        public Nullable<System.Guid> ServiceID { get; set; }
        public Nullable<System.Guid> ContactID { get; set; }
        public Nullable<int> FundingSource { get; set; }
        public int FundingAmount { get; set; }
        public Nullable<System.DateTime> FundingStart { get; set; }
        public Nullable<System.DateTime> FundingEnd { get; set; }
        public Nullable<int> FundingNeeds { get; set; }
        public Nullable<int> ContinuationAmount { get; set; }
        public string ContinuationDetails { get; set; }
        public string FundraisingText { get; set; }
        public string FundraisingWhy { get; set; }
        public Nullable<int> FundraisingNeeds { get; set; }
        public Nullable<System.DateTime> FundraisingRequired { get; set; }
        public Nullable<bool> FundraisingComplete { get; set; }
        public Nullable<System.DateTime> CompletedDate { get; set; }
        public Nullable<bool> DonorAnonymous { get; set; }
        public Nullable<int> DonorAmount { get; set; }
        public Nullable<System.DateTime> DonationDate { get; set; }
        public Nullable<bool> DonationIncremental { get; set; }
    
        public virtual tblContact tblContact { get; set; }
        public virtual tblService tblService { get; set; }
    }
}
