//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceDirectory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPremis
    {
        public tblPremis()
        {
            this.tblFacilities = new HashSet<tblFacility>();
            this.tblMinorWorks = new HashSet<tblMinorWork>();
            this.tblPremisesOpeningTimes = new HashSet<tblPremisesOpeningTime>();
            this.tblServicePremises = new HashSet<tblServicePremise>();
            this.tblVolunteerings = new HashSet<tblVolunteering>();
            this.tblPremises1 = new HashSet<tblPremis>();
            this.tblPremises = new HashSet<tblPremis>();
            this.tblReferenceDatas = new HashSet<tblReferenceData>();
        }
    
        public int PremisesID { get; set; }
        public string PremisesName { get; set; }
        public Nullable<int> AddressID { get; set; }
        public string AddressLine1 { get; set; }
        public string LocationName { get; set; }
        public string KnowAs { get; set; }
        public Nullable<int> OrgID { get; set; }
        public string LocationStatus { get; set; }
        public string AddressLine2 { get; set; }
        public string AddressLine3 { get; set; }
        public Nullable<bool> PrimaryLocation { get; set; }
        public Nullable<bool> LocationManaged { get; set; }
        public string LocationDescription { get; set; }
        public string PhoneNumber { get; set; }
        public string Fax { get; set; }
        public Nullable<int> MinicomNumber { get; set; }
        public Nullable<System.DateTime> FlagDate { get; set; }
        public Nullable<bool> IsSpecialist { get; set; }
        public Nullable<int> MediaContactID { get; set; }
        public Nullable<int> CateringContactID { get; set; }
        public Nullable<int> CateringType { get; set; }
        public string Network { get; set; }
        public string ClientITFacilities { get; set; }
        public string LocalDemographicNotes { get; set; }
        public Nullable<bool> RoomAvailability { get; set; }
        public string TravelDetails { get; set; }
        public string Bus { get; set; }
        public string Rail { get; set; }
        public string Airport { get; set; }
        public Nullable<int> HostingContactID { get; set; }
        public Nullable<int> ParkingSpaces { get; set; }
        public string ParkingAlternative { get; set; }
        public Nullable<decimal> RoomRate { get; set; }
        public Nullable<decimal> BBRate { get; set; }
        public Nullable<decimal> DBBRate { get; set; }
        public Nullable<decimal> DDRate { get; set; }
        public Nullable<decimal> TwentyfourhourRate { get; set; }
        public Nullable<decimal> TeaAndCoffee { get; set; }
        public Nullable<decimal> NoMeetingRoom { get; set; }
        public Nullable<decimal> MeetingRoomRate { get; set; }
        public Nullable<decimal> NegRoomRate { get; set; }
        public Nullable<decimal> BBNegRate { get; set; }
        public Nullable<decimal> DBBNegRate { get; set; }
        public Nullable<decimal> DDNegRate { get; set; }
        public Nullable<decimal> TwentyfourhourNegRate { get; set; }
        public Nullable<System.DateTime> LastDate { get; set; }
        public Nullable<System.DateTime> ReDate { get; set; }
        public string PreferredStatus { get; set; }
        public string Comment { get; set; }
        public string Coding { get; set; }
    
        public virtual tblAddress tblAddress { get; set; }
        public virtual tblContact tblContact { get; set; }
        public virtual tblContact tblContact1 { get; set; }
        public virtual tblContact tblContact2 { get; set; }
        public virtual ICollection<tblFacility> tblFacilities { get; set; }
        public virtual ICollection<tblMinorWork> tblMinorWorks { get; set; }
        public virtual tblOrganisation tblOrganisation { get; set; }
        public virtual tblReferenceData tblReferenceData { get; set; }
        public virtual ICollection<tblPremisesOpeningTime> tblPremisesOpeningTimes { get; set; }
        public virtual ICollection<tblServicePremise> tblServicePremises { get; set; }
        public virtual ICollection<tblVolunteering> tblVolunteerings { get; set; }
        public virtual ICollection<tblPremis> tblPremises1 { get; set; }
        public virtual ICollection<tblPremis> tblPremises { get; set; }
        public virtual ICollection<tblReferenceData> tblReferenceDatas { get; set; }
    }
}
