//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceDirectory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPremisesOpeningTime
    {
        public System.Guid PremisesOpeningTimeID { get; set; }
        public Nullable<System.Guid> PremisesID { get; set; }
        public string WeekendDay { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
    
        public virtual tblPremis tblPremis { get; set; }
    }
}
