//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceDirectory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblReferenceData
    {
        public tblReferenceData()
        {
            this.tblFacilities = new HashSet<tblFacility>();
            this.tblPremises = new HashSet<tblPremis>();
            this.tblContacts = new HashSet<tblContact>();
            this.tblOrganisations = new HashSet<tblOrganisation>();
            this.tblPremises1 = new HashSet<tblPremis>();
            this.tblServices = new HashSet<tblService>();
            this.tblServices1 = new HashSet<tblService>();
        }
    
        public System.Guid RefID { get; set; }
        public int RefCode { get; set; }
        public string RefValue { get; set; }
    
        public virtual ICollection<tblFacility> tblFacilities { get; set; }
        public virtual tblGroupReference tblGroupReference { get; set; }
        public virtual ICollection<tblPremis> tblPremises { get; set; }
        public virtual ICollection<tblContact> tblContacts { get; set; }
        public virtual ICollection<tblOrganisation> tblOrganisations { get; set; }
        public virtual ICollection<tblPremis> tblPremises1 { get; set; }
        public virtual ICollection<tblService> tblServices { get; set; }
        public virtual ICollection<tblService> tblServices1 { get; set; }
    }
}
