//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceDirectory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRole
    {
        public tblRole()
        {
            this.tblUsers = new HashSet<tblUser>();
        }
    
        public System.Guid RoleID { get; set; }
        public string RoleName { get; set; }
        public string RoleDescription { get; set; }
    
        public virtual ICollection<tblUser> tblUsers { get; set; }
    }
}
