//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceDirectory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblServicePremise
    {
        public System.Guid ServiceID { get; set; }
        public System.Guid PremisesID { get; set; }
        public string ProjectCode { get; set; }
    
        public virtual tblPremis tblPremis { get; set; }
        public virtual tblService tblService { get; set; }
    }
}
