//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceDirectory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTrustRegion
    {
        public tblTrustRegion()
        {
            this.tblTrustDistricts = new HashSet<tblTrustDistrict>();
        }
    
        public int TrustRegionID { get; set; }
        public Nullable<int> CountryID { get; set; }
        public string TrustRegionName { get; set; }
        public string TrustRegionDescription { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual tblCountry tblCountry { get; set; }
        public virtual ICollection<tblTrustDistrict> tblTrustDistricts { get; set; }
    }
}
