//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceDirectory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTown
    {
        public tblTown()
        {
            this.tblAddresses = new HashSet<tblAddress>();
        }
    
        public System.Guid TownID { get; set; }
        public Nullable<System.Guid> CountyID { get; set; }
        public string TownName { get; set; }
        public string TownDescription { get; set; }
    
        public virtual ICollection<tblAddress> tblAddresses { get; set; }
        public virtual tblCounty tblCounty { get; set; }
    }
}
