//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceDirectory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTrustDistrict
    {
        public int TrustDistrictID { get; set; }
        public Nullable<int> TrustRegionID { get; set; }
        public string TrustDistrictName { get; set; }
        public string TrustDistrictDescription { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual tblTrustRegion tblTrustRegion { get; set; }
    }
}
