//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceDirectory.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class tblTeam
    {
        public System.Guid TeamID { get; set; }
        public Nullable<System.Guid> DepartmentID { get; set; }
        public Nullable<System.Guid> ContactID { get; set; }
        public Nullable<System.Guid> AddressID { get; set; }
        public Nullable<System.Guid> BusinessID { get; set; }

        [Required(ErrorMessage="Please input the team name!")]
        [StringLength(200, ErrorMessage="Team name is not more than 200 characters!")]
        public string TeamName { get; set; }

        [StringLength(1000, ErrorMessage = "Short description is not more than 1000 characters!")]
        public string ShortDescription { get; set; }

        [StringLength(2000, ErrorMessage = "Full description is not more than 2000 characters!")]
        public string FullDescription { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string AddressLine3 { get; set; }

        [StringLength(20, ErrorMessage = "Phone number is not more than 20 characters!")]
        public string PhoneNumber { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string WebAddress { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual tblAddress tblAddress { get; set; }
        public virtual tblBusinessType tblBusinessType { get; set; }
        public virtual tblContact tblContact { get; set; }
        public virtual tblDepartment tblDepartment { get; set; }
    }
}
